### ISSUE TITLE
Exception: Some error occurred during recording, verify your provided options

### ISSUE THREAD

**Issue by abbasalis** [daudmalik06/PhpScreenRecorder#5]
$screenRecorder = new ScreenRecorder();
        $screenRecorder->setScreenSizeToCapture(1920,1080);
        $screenRecorder->startRecording('/var/www/html/testing/automation-testvideos/testvideo.flv');
        $this->browse(function (Browser $browser) {
            $browser->visit('https://github.com')->assertSee('GitHub');
        });
        $screenRecorder->stopRecording();
        print "video is saved at :\"".$screenRecorder->getVideo().'"'.PHP_EOL;

When I try to record the above test using your library, I got the following error (video not saved in the location)

There was 1 error:

Exception: Some error occurred during recording, verify your provided options

/var/www/html/laravel5.4.23/vendor/dawood/phpscreenrecorder/src/ScreenRecorder.php:108
/var/www/html/laravel5.4.23/tests/Browser/ExampleTest.php:25

Is there any problem with my code or any other thing that I need to do to fix this ?

**Comment by daudmalik06** [comment]
Hey Abbas Ali,


please also post some environment details,
that would help me to replicate the issue,
please note that library is using screen recorder so gui must be available
for screen recorder to work and make sure the directory where you are
trying to write has necessary write permissions ,

I'll investigate and will update you as soon as possible

Thanks



On Feb 19, 2018 8:53 AM, "Abbas Ali" <notifications@github.com> wrote:

   **$screenRecorder = new ScreenRecorder();
    $screenRecorder->setScreenSizeToCapture(1920,1080);
    $screenRecorder->startRecording('/var/www/html/testing/automation-testvideos/testvideo.flv');**
    $this->browse(function (Browser $browser) {
        $browser->visit('https://github.com')->assertSee('GitHub');
    });
    **$screenRecorder->stopRecording();
    print "video is saved at :\"".$screenRecorder->getVideo().'"'.PHP_EOL;**

When I try to record the above test using your library, I got the following
error (video not saved in the location)

There was 1 error:

**Exception: Some error occurred during recording, verify your provided
options

/var/www/html/laravel5.4.23/vendor/dawood/phpscreenrecorder/src/
ScreenRecorder.php:108
/var/www/html/laravel5.4.23/tests/Browser/ExampleTest.php:25**

Is there any problem with my code or any other thing that I need to do to
fix this ?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/daudmalik06/PhpScreenRecorder/issues/5>, or mute the
thread

**Comment by daudmalik06** [comment]
Hey @abbasalis 
please also post some environment details,
that would help me to replicate the issue, 
please note that library is using screen recorder so gui must be available for screen recorder to work and make sure the directory where you are trying to write has necessary write permissions ,

I'll investigate and will update you as soon as possible

Thanks

**Comment by abbasalis** [comment]
@daudmalik06 

I am running and recording tests under laravel 5.4. 
OS: linux, ubuntu 17.10  
PHP version. 7.0

I can see the browser running the tests and after the browser got closed (test was done), I got the above error (i mean inside stopRecording function).

Also, the directory have write permissions.

In stopRecording function, process Id can't be fetched, so this error was thrown.
Please check and let me know your comments.

**Comment by daudmalik06** [comment]
hey sorry for late response , 
can you check the execution permissions of `vendor/PhpScreenRecorder/src/bin/ffmpegLinux`
